spring.application.name=laBonneListe

spring.datasource.url=jdbc:postgresql://postgres:5432/labonneliste
spring.datasource.username=admin
spring.datasource.password=password

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true